import os
from datetime import datetime
from typing import List
from attacks.prompt_injection.direct_injection import AttackResult


TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AgentShield Security Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', sans-serif; background: #0f1117; color: #e0e0e0; padding: 30px; }}
        .header {{ background: linear-gradient(135deg, #1a1f2e, #2d3561); padding: 30px; border-radius: 12px; margin-bottom: 30px; border-left: 5px solid #4f8ef7; }}
        .header h1 {{ font-size: 28px; color: #4f8ef7; margin-bottom: 8px; }}
        .header p {{ color: #888; font-size: 14px; }}
        .summary {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 15px; margin-bottom: 30px; }}
        .summary-card {{ background: #1a1f2e; padding: 20px; border-radius: 10px; text-align: center; }}
        .summary-card .count {{ font-size: 36px; font-weight: bold; margin-bottom: 5px; }}
        .summary-card .label {{ font-size: 12px; color: #888; text-transform: uppercase; }}
        .critical {{ color: #ff4757; border-top: 3px solid #ff4757; }}
        .high {{ color: #ff6b35; border-top: 3px solid #ff6b35; }}
        .medium {{ color: #ffa502; border-top: 3px solid #ffa502; }}
        .low {{ color: #2ed573; border-top: 3px solid #2ed573; }}
        .safe {{ color: #1e90ff; border-top: 3px solid #1e90ff; }}
        .section-title {{ font-size: 18px; color: #4f8ef7; margin-bottom: 15px; padding-bottom: 8px; border-bottom: 1px solid #2d3561; }}
        .finding {{ background: #1a1f2e; border-radius: 10px; padding: 20px; margin-bottom: 15px; border-left: 4px solid #333; }}
        .finding.CRITICAL {{ border-left-color: #ff4757; }}
        .finding.HIGH {{ border-left-color: #ff6b35; }}
        .finding.MEDIUM {{ border-left-color: #ffa502; }}
        .finding.LOW {{ border-left-color: #2ed573; }}
        .finding.SAFE {{ border-left-color: #1e90ff; }}
        .finding-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }}
        .finding-title {{ font-size: 15px; font-weight: 600; color: #e0e0e0; }}
        .badge {{ padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; }}
        .badge.CRITICAL {{ background: #ff475720; color: #ff4757; }}
        .badge.HIGH {{ background: #ff6b3520; color: #ff6b35; }}
        .badge.MEDIUM {{ background: #ffa50220; color: #ffa502; }}
        .badge.LOW {{ background: #2ed57320; color: #2ed573; }}
        .badge.SAFE {{ background: #1e90ff20; color: #1e90ff; }}
        .finding-detail {{ font-size: 13px; color: #888; margin-bottom: 6px; }}
        .finding-detail span {{ color: #ccc; }}
        .prompt-box {{ background: #0f1117; padding: 10px; border-radius: 6px; font-size: 12px; color: #aaa; margin-top: 8px; font-family: monospace; }}
        .recommendation {{ background: #1e2d1e; padding: 10px; border-radius: 6px; font-size: 12px; color: #2ed573; margin-top: 8px; }}
        .footer {{ text-align: center; color: #444; font-size: 12px; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ AgentShield Security Report</h1>
        <p>Agent Tested: <strong>{agent_name}</strong> &nbsp;|&nbsp; Scan Date: <strong>{scan_date}</strong> &nbsp;|&nbsp; Total Attacks: <strong>{total_attacks}</strong> &nbsp;|&nbsp; Vulnerabilities Found: <strong>{vulnerabilities_found}</strong></p>
    </div>

    <div class="summary">
        <div class="summary-card critical">
            <div class="count">{critical}</div>
            <div class="label">Critical</div>
        </div>
        <div class="summary-card high">
            <div class="count">{high}</div>
            <div class="label">High</div>
        </div>
        <div class="summary-card medium">
            <div class="count">{medium}</div>
            <div class="label">Medium</div>
        </div>
        <div class="summary-card low">
            <div class="count">{low}</div>
            <div class="label">Low</div>
        </div>
        <div class="summary-card safe">
            <div class="count">{safe}</div>
            <div class="label">Safe</div>
        </div>
    </div>

    <p class="section-title">Detailed Findings</p>
    {findings_html}

    <div class="footer">
        Generated by AgentShield — AI Agent Security Testing Framework
    </div>
</body>
</html>
"""

FINDING_TEMPLATE = """
<div class="finding {severity}">
    <div class="finding-header">
        <div class="finding-title">{attack_name}</div>
        <span class="badge {severity}">{severity}</span>
    </div>
    <div class="finding-detail">Attack Type: <span>{attack_type}</span></div>
    <div class="finding-detail">Vulnerable: <span>{vulnerable}</span></div>
    <div class="prompt-box">Prompt: {prompt}</div>
    <div class="prompt-box">Response: {response}</div>
    <div class="recommendation">💡 {recommendation}</div>
</div>
"""


class HTMLReporter:

    def generate(self, results: List[AttackResult], agent_name: str = "unknown") -> str:
        os.makedirs("reports", exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = f"reports/agentshield_{agent_name}_{timestamp}.html"

        severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "SAFE": 0}
        for r in results:
            severity_counts[r.severity] = severity_counts.get(r.severity, 0) + 1

        findings_html = ""
        for r in results:
            findings_html += FINDING_TEMPLATE.format(
                severity=r.severity,
                attack_name=r.attack_name,
                attack_type=r.attack_type,
                vulnerable="⚠️ Yes" if r.vulnerability_detected else "✅ No",
                prompt=r.prompt_used[:200],
                response=r.agent_response[:300],
                recommendation=r.recommendation
            )

        html = TEMPLATE.format(
            agent_name=agent_name,
            scan_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            total_attacks=len(results),
            vulnerabilities_found=sum(1 for r in results if r.vulnerability_detected),
            critical=severity_counts["CRITICAL"],
            high=severity_counts["HIGH"],
            medium=severity_counts["MEDIUM"],
            low=severity_counts["LOW"],
            safe=severity_counts["SAFE"],
            findings_html=findings_html
        )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return filepath